### ISSUE TITLE
Add API authentication 

### ISSUE THREAD

**Issue by bbhupen** [bbhupen/Farmer-Support-Backend-API#2]
Add API Authentication. Any authentication mechanism will work. JWT is preferred though.

**Comment by Preet-taparia** [comment]
hey i would like to work on it can you please assign this to me

**Comment by bbhupen** [comment]
@Preet-taparia that's great. Get going

**Comment by bbhupen** [comment]
@Preet-taparia 
hey what's up 
why did you closed the pr?? any prob?

**Comment by Preet-taparia** [comment]
Hey, can you please add “HACKTOBERFEST-ACCEPTED” label and other related information regarding HACKTOBERFEST on your repo so that more participation can come.

**Comment by bbhupen** [comment]
@Preet-taparia sure

**Comment by Preet-taparia** [comment]
Well, I meant label of HACKTOBERFEST-ACCEPTED on PR #5.
and
Add the “hacktoberfest” topic to your repository.
Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub Projects.
Add a CONTRIBUTING.md file with contribution guidelines to your repository.
so that contribution due to hacktoberfest will happen
